# Generated by Django 4.2.5 on 2023-09-21 12:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("kitchen", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dish",
            options={"ordering": ["name"], "verbose_name_plural": "dishes"},
        ),
        migrations.AlterModelOptions(
            name="dishtype",
            options={"ordering": ["-name"]},
        ),
    ]
